title: SoloITGuy Projects 
logo: "/images/profile.png" 
description: >
  Solo guy trying to create some tools for everyday use.
  <br><br>
  <p class="special-paragraph">Page created just to comply with a ridiculous Unity rule to be able to publish an asset in the asset store.</p>
  <br><br>
  lonelyitguystudio@gmail.com
  <br><br>
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0
